In [2]:
import numpy as np
lst=[4,5,6]
lst*5
arr=np.array([4,5,6])
arr*5

array([20, 25, 30])

In [ ]:
#Python grade example
#You’re a teacher who has just graded your students on a recent test.
#Unfortunately, you may have made the test too challenging, and most of the students did worse than expected. 
#To help everybody out, you’re going to curve everyone’s grades.

In [ ]:
#You’ll take whatever the average score is  
#Additionally, you’ll make sure that the curve doesn’t accidentally 
#hurt your students’ grades or the student does better than 100%.

In [4]:
import numpy as np
CURVE_CENTER = 80
grades = np.array([72, 35, 64, 88, 51, 90, 74, 12]) 

def curve(grades):
    average = grades.mean()
    #print("average is", average)
    change = CURVE_CENTER - average
    #vectorisation and broadcasting [72, 35, 64, 88,....] + 19.25, 19.25, 19.25........
    new_grades = grades + change
    #print(new_grades)
    return np.clip(new_grades, 55, 99)

curve(grades)



array([91.25, 55.  , 83.25, 99.  , 70.25, 99.  , 93.25, 55.  ])

# Shapes

In [7]:
a = np.arange(0,80,10)
print(a)
#big data  
y = a[[1, 2, -3]]
print(y)

s=np.take(a,[1,2,-3])
print(s)


[ 0 10 20 30 40 50 60 70]
[10 20 50]
[10 20 50]


In [11]:
X=np.array([[0,1,2,3],
            [4,5,6,7],
            [8,9,10,11]])

#Like with standard indexing, the first index
#refers to the row, and the second to the column:
Row=np.array([0,1,2])
Col=np.array([2,1,3])
X[Row,Col]
#or
#X[2, (1,0,2)]    # shows ([2,5,11])


array([ 2,  5, 11])

In [13]:
a = np.arange(0,20).reshape(5,4)
print(a.sum())
print(a)

190
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [15]:
colsum=a.sum(axis=0)
rowsum=a.sum(axis=1)
print(colsum.shape,"\t",rowsum.shape)
print("col wise total",colsum)
print("row wise total",rowsum)
print(a.sum(axis=-1))
#1. generate single dim array 
#2.to add in numpy array vertically , transpose
#3.concatenate main array and single dimensional array after transposing

(4,) 	 (5,)
col wise total [40 45 50 55]
row wise total [ 6 22 38 54 70]
[ 6 22 38 54 70]


In [77]:
#import numpy as np

temperatures = np.array([
     29.3, 42.1, 18.8, 16.1, 38.0, 12.5,
    12.6, 49.9, 38.6, 31.3, 9.2, 22.2]).reshape(3, 2, 2)
#or reshape(2,3,2)
print(temperatures.shape)

print(temperatures)
#Q extract the 2nd weeks temperature of last three days


(3, 2, 2)
[[[29.3 42.1]
  [18.8 16.1]]

 [[38.  12.5]
  [12.6 49.9]]

 [[38.6 31.3]
  [ 9.2 22.2]]]


In [78]:
a=np.swapaxes(temperatures,1,2)
print(a)
a.shape

[[[29.3 18.8]
  [42.1 16.1]]

 [[38.  12.6]
  [12.5 49.9]]

 [[38.6  9.2]
  [31.3 22.2]]]


(3, 2, 2)

In [85]:
#eng p  c  m  of 4 students
table[:,0]
table[:,1]
table[:,2]

table = np.array([
                    [4,5 , 6, 7],
                    [5, 3, 7, 1],
                    [2, 6, 7 ,9],
                    [10, 9, 8,8],
                    [4, 3, 2, 0],
                  ])
#Q1 AVERAGE OF EVERY STUDENT
#table[:,1].mean(axis=0)   #rowwise
table.shape


(5, 4)

In [38]:
table[:,:].mean(axis=0) 

array([5.25, 5.25, 6.  , 4.5 ])

# Axis

In [40]:
for i in range(4):
    avg=table[i,:]
    print("first student avg",avg.sum()/4)

import numpy as np 
   
arr1 = np.array([5,3,7,1]) 
arr2 = np.array([2,16,7,9])
arr3 = np.array([1,1,1,1])
arr4 = np.array([4,3,2,0]) 
   
avg = (arr1 + arr2 + arr3 +  arr4) / 2
  
print("Average of Every Student:\n" , 
      avg)

first student avg 4.0
first student avg 6.0
first student avg 8.75
first student avg 2.25
Average of Every Student:
 [ 6.  11.5  8.5  5.5]


In [88]:
#Understanding axis
#how .max() behaves by default, with no axis argument, 
#and how it changes functionality depending on which axis you specify when you do supply an argument:
import numpy as np

table = np.array([
[4, 5, 7, 8],  [9,8
[5, 3, 7, 1],   8,5
[2, 6, 7 ,9],   8,6
[1, 1, 10, 1],  6,8
[4, 3, 2, 0],   7,9
               ]
) ]
#concat
#vstack, stack
#append
print(table.max())
#col wise
print(table.sum(axis=0))
#rowwise  which are max marks of every student
print(table.sum(axis=1))


10
[16 18 33 19]
[24 16 24 13  9]


In [ ]:
#Durer's magic square, a best-known and most enigmatic, with magic constant 34.
#The number square below has some amazing properties. 
#If you add up any of the rows, columns, or diagonals, then you’ll get the same number,
#That’s also what you’ll get if you add up each of the four quadrants,
#the center four squares, the four corner squares,
#or the four corner squares of any of the contained 3 × 3 grids. 

In [ ]:
import numpy as np

square = np.array([
[16, 3, 2, 13],
[5, 10, 11, 8],
[9, 6, 7, 12],
[4, 15, 14, 1]
 ])

a = square[:,0]
columns = np.sum(square,axis=1)
rows = np.sum(square,axis=0)
count = 0;
for i in columns:
  if i != 34:
    print("Is not a magic sqaure")
  else:
    print("Is magic sqaure")

In [21]:
##Durer's magic square
#Inside the for loop, you verify that all the rows and all the columns add up to 34. 
#After that, using selective indexing, you verify 
#that each of the quadrants also adds up to 34.
import numpy as np

square = np.array([
[16, 3,   2,  13], 
[5,  10, 11,   8],
[9,  6,   7,  12],
[4, 15,  14,   1]
 ])

for i in range(4):
    print(square[:,i]==34)
    
for i in range(4):
    print(square[:, i].sum() == 34)
    print(square[i, :].sum() == 34)

#the first quadrant
print( square[:2, :2].sum() == 34)

#third quadrant
print( square[2:, :2].sum() == 34)

#second quadrant
print( square[:2, 2:].sum() == 34)

#4th quadrant
print( square[2:, 2:].sum() == 34)


[False False False False]
[False False False False]
[False False False False]
[False False False False]
True
True
True
True
True
True
True
True
True
True
True
True


In [97]:

square=np.array([[16,3,2,13],
                 [5,10,11,8],
                 [9,6,7,12],
                 [4,15,14,1]])

def magic():
    print("magic square")
def notmagic():
    print("not magic square")
for i in range(4):
    sq=square.sum(axis=0)
    sq1=square.sum(axis=1)
    
    if square[(0,1,2,3),(0,1,2,3)].sum()==34:
        if sq[i]==34:
            if sq1[i]==34:
                if (square[0:2,0:2].sum() ==34) and (square[2:,2:].sum() ==34) and (square[2:,0:2].sum()==34) and (square[0:2,2:].sum()  ==34):
                     magic()
                else:
                    notmagic()
            else:
                notmagic()
        else:
            notmagic()
    else:
        notmagic()



magic square
magic square
magic square
magic square


In [109]:

import numpy as np
 
square1 = np.array([
[16, 3, 2, 13],
[5, 10, 11, 8],
[9, 6, 7, 12],
[4, 15, 14, 1]
 ])
 
if sum(square1[[0,0,1,1],[0,1,0,1]]) == sum(square1[[0,0,1,1],[2,3,2,3]]) == sum(square1[[2,2,3,3],[0,1,0,1]]) == sum(square1[[2,2,3,3],[2,3,2,3]]):
    print("True 1")
    if sum(square1[0]) == sum(square1[1]) == sum(square1[2]) == sum(square1[3]):
        print("True 2")
        if sum(square1[:,0]) == sum(square1[:,1]) == sum(square1[:,2]) == sum(square1[:,3]):
            print("True 3")
            if sum(square1[[0,1,2,3],[0,1,2,3]]) == sum(square1[:,3]):
                print("True")


TypeError: 'numpy.ndarray' object is not callable

In [42]:
import numpy as np
square=np.array([[16,3,2,13],
                 [5,10,11,8],
                 [9,6,7,12],
                 [4,15,14,1]])
s=square.sum(axis=0)
print(s)
r=square.sum(axis=1)
print(r)
d= square[:2,:2].sum()
print((d))
e= square[2:,2:].sum()
print((e))
f= square[2:,:2].sum()
print((f))
g= square[:2,2:].sum()
print((g))
if  s[i]==r[i] and d==e==f==g:
    print("it's a magic square")
else:
    print("it's not a magic square")

[34 34 34 34]
[34 34 34 34]
34
34
34
34
it's a magic square


In [44]:
square=np.array([
[16,3,2,13],
[5,10,11,8],
[9,6,7,12],
[4,15,14,1],                
])
for i in range(4):
  sum_row=square[i,:].sum()
  print("row",sum_row.sum())
for i in range(4):
  col_row=square[:,i].sum()
  print("column",col_row.sum())
first_quad=print(square[0:2,0:2].sum())
second_quad=print(square[0:2,2:4].sum())
third_quad=print(square[2:4,0:2].sum())
four_quad=print(square[2:4,2:4].sum())
if(first_quad == second_quad ==third_quad ==four_quad):
  print("its a magic square")
else:
  print("not a magic square")


row 34
row 34
row 34
row 34
column 34
column 34
column 34
column 34
34
34
34
34
its a magic square


In [106]:
import numpy as np
durerarr = np.array([[16,3,2,13],
                   [5,10,11,8],
                    [9,6,7,12],
                   [4,15,14,1]])
for i in durerarr:
    if sum(i) == 34:
        r = sum(i)
        continue
    else:
        print("no")
        break
print("All row sum = 34")
print(r)
for i in range(4):
    if sum(durerarr[:,i]) == 34:
        c = sum(durerarr[:,i])
        continue
    else:
        print("no")
print("All column sum = 34")
print(c)
d1 = durerarr[:2,:2]
d2 = durerarr[2:,2:]
d3 = durerarr[:2,2:]
d4 = durerarr[2:,:2]
if np.sum(d1) ==34 and np.sum(d2) == 34 and np.sum(d3) and np.sum(d4) == 34 and r ==34 and c ==34:
    print("it is durer matrix")
else:
    print("not")

All row sum = 34
34
All column sum = 34
34
it is durer matrix


# Indexing

# Masking and Filtering

In [ ]:
#to filter your data based on more complicated nonuniform or nonsequential criteria

In [ ]:
import numpy as np
#generates n numbers evenly distributed between a minimum and a maximum, 
#which is useful for evenly distributed sampling in scientific plotting.
#because the space between 5 and 50 doesn’t divide evenly by 24,
#the resulting numbers are floating numbers
#You specify a dtype of int to force the function to round down and give you whole integers.
# -1 signifies that NumPy should just figure out how big that 
#particular axis needs to be based on the size of the other axes. 
#In this case, with 24 values and a size of 4 in axis 0, axis 1 ends up
#with a size of 6.


In [48]:
numbers = np.linspace(5, 50, 24, dtype=int).reshape(4, 6)
numbers


array([[ 5,  6,  8, 10, 12, 14],
       [16, 18, 20, 22, 24, 26],
       [28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50]])

In [116]:
#creates the mask by performing a vectorized Boolean computation
mask= numbers % 4 == 0

In [54]:
#uses this mask to index into the original numbers array. 
#This causes the array to lose its original shape, reducing it to one dimension 
numbers[mask]

array([ 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48])

In [55]:
by_four = numbers[numbers % 4 == 0]

In [56]:
# an anonymous filtering array created inline, inside the selection brackets.
by_four

array([ 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48])

In [ ]:
#Example : The normal distribution is a probability distribution in which 
#roughly 95.45% of values occur  within two standard deviations of the mean.

#import numpy as np

#from numpy.random import default_rng

#rng = default_rng()

#values = rng.standard_normal(10000)

#values[:5]



In [ ]:
#strange-looking syntax to combine filter conditions: a binary & operator. 
#Why would that be the case? It’s because NumPy designates & and | as the vectorized, 
#element-wise operators to combine Booleans. If you try to do A and B, then you’ll get 
#a warning about how the truth value for an array is weird, 
#because the and is operating on the truth value of the whole array, not element by element.

# Transposing, Sorting, and Concatenating

In [120]:
#When you calculate the transpose of an array, the row and column 
#indices of every element are switched.

import numpy as np

a = np.array([
    [1, 2],
    [3, 4],
    [5, 6],
])

a.T


array([[1, 3, 5],
       [2, 4, 6]])

In [ ]:
a.transpose()

# Sorting

In [49]:
# importing libraries 
import numpy as np 
  
# sort along the first axis (col wise)
a = np.array([[12, 15], 
              [10, 1]]) 
arr1 = np.sort(a, axis = 0)         
print ("Along first axis : \n", arr1)         
    
# sort along the last axis  (row wise)
a = np.array([[10, 15], 
              [12, 1]]) 
arr2 = np.sort(a, axis = -1)         
print ("\nAlong last axis : \n", arr2) 
   
a = np.array([[12, 15], 
              [10, 1]]) 
#None flattens the array and performs a global sort.
arr1 = np.sort(a, axis = None)         
print ("\nAlong none axis : \n", arr1) 



Along first axis : 
 [[10  1]
 [12 15]]

Along last axis : 
 [[10 15]
 [ 1 12]]

Along none axis : 
 [ 1 10 12 15]


In [158]:
np.sort?

In [50]:
#Omitting the axis argument automatically selects the last and
#innermost dimension, which is the rows in this example. 

import numpy as np

data = np.array([[7, 1, 4],
                 [8, 6, 5],
                 [1, 2, 3]])

np.sort(data)   #by default row-wise sorting done

array([[1, 4, 7],
       [5, 6, 8],
       [1, 2, 3]])

In [51]:
np.array([[1, 4, 7],
          [5, 6, 8],
          [1, 2, 3]])

np.sort(data, axis=None)


array([1, 1, 2, 3, 4, 5, 6, 7, 8])

In [53]:
print(data)
np.sort(data, axis=0)


[[7 1 4]
 [8 6 5]
 [1 2 3]]


array([[1, 1, 3],
       [7, 2, 4],
       [8, 6, 5]])

# Concatenation

In [110]:
#One important stumbling block to note is that all these functions take a 
#tuple of arrays as their first argument rather than a variable number of
#arguments as you might expect. 
#You can tell because there’s an extra pair of parentheses.
a = np.array([
               [4, 8],
               [6, 1]    
              ])       
b = np.array([
              [3, 5],  
              [7, 2],
              [3, 4]
              
             ])

np.vstack((a, b))  #axis 1


array([[4, 8],
       [6, 1],
       [3, 5],
       [7, 2],
       [3, 4]])

In [111]:
a= np.array([
               [4, 8],
               [6, 1]
              ])

b = np.array([
              [3, 5],
              [7, 2]
             ])
np.concatenate((a, b))

array([[4, 8],
       [6, 1],
       [3, 5],
       [7, 2]])

In [56]:
np.vstack((a, b))

array([[4, 8],
       [6, 1],
       [3, 5],
       [7, 2]])

In [72]:
a= np.array([
               [4, 8],
               [6, 1]
              ])

b = np.array([
              [3, 5],
              [7, 2]
             ])
np.concatenate((a, b), axis=None)

array([4, 8, 6, 1, 3, 5, 7, 2])

In [ ]:
# NumPy has a special kind of array, called a record array or structured array, 
#with which you can specify a type and, optionally,a name on a per-column basis

In [58]:
In [1]: import numpy as np

data = np.array([
("joe", 32, 6),
("mary", 15, 20),
("felipe", 80, 100),
("beyonce", 38, 9001),], dtype=[("name", str, 10), ("age", int), ("power", int)])

data[0]


('joe', 32, 6)

In [59]:
data["name"]


array(['joe', 'mary', 'felipe', 'beyonce'], dtype='<U10')

In [60]:
a=data[data["power"] > 9000]["name"]
a


array(['beyonce'], dtype='<U10')

In [61]:
data[data["age"] > 20]

array([('joe', 32,    6), ('felipe', 80,  100), ('beyonce', 38, 9001)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('power', '<i4')])

In [88]:
np.sort(data[data["age"] > 20], order="power")["name"]

array(['joe', 'felipe', 'beyonce'], dtype='<U10')

In [89]:

i16 = np.dtype(np.int16)
print(i16)

lst = [ [3.4, 8.7, 9.9], 
        [1.1, -7.8, -0.7],
        [4.1, 12.3, 4.8] ]

A = np.array(lst, dtype=i16)
A

int16


array([[ 3,  8,  9],
       [ 1, -7,  0],
       [ 4, 12,  4]], dtype=int16)

In [90]:

arr=np.array([[14, 17, 12, 33, 44],
              [15, 6, 27, 8, 19],
              [23, 2, 54, 1, 4]])
print("\nSum of arr : ", np.sum(arr))
print("Sum of arr(uint8) : ", np.sum(arr, dtype = np.uint8))
print("Sum of arr(float32) : ", np.sum(arr, dtype = np.float32))
print ("\nIs np.sum(arr).dtype == np.uint : ",
       np.sum(arr).dtype == np.uint)


Sum of arr :  279
Sum of arr(uint8) :  23
Sum of arr(float32) :  279.0

Is np.sum(arr).dtype == np.uint :  False


In [93]:
new=np.empty([3])
print("\nSum of arr : ", np.sum(arr))
print("Sum of arr(axis = 0) : ", np.sum(arr, axis = 0))
print("Sum of arr(axis = 1) : ", np.sum(arr, axis = 1,out=new))
print("new is", new)
print("\nSum of arr (keepdimension is True): \n",
      np.sum(arr, axis = 1, keepdims = True)) 
print("new is ", new)


Sum of arr :  279
Sum of arr(axis = 0) :  [52 25 93 42 67]
Sum of arr(axis = 1) :  [120.  75.  84.]
out is [120.  75.  84.]

Sum of arr (keepdimension is True): 
 [[120]
 [ 75]
 [ 84]]
new is  [120.  75.  84.]


In [62]:
a = np.array([[1, 2], [3, 4]])
print(a)
print()
b = np.array([[5, 6]])
print(b)
print()
arr=np.concatenate((a, b), axis=0)
print(arr)
arr1=np.concatenate((a,b.T), axis=1)
print(arr1)
arr2=np.concatenate((a, b), axis=None)
print(arr2)

[[1 2]
 [3 4]]

[[5 6]]

[[1 2]
 [3 4]
 [5 6]]
[[1 2 5]
 [3 4 6]]
[1 2 3 4 5 6]


In [99]:
# Python code to demonstrate
# adding columns in numpy array
 
import numpy as np
 
ini_array = np.array([[1, 2, 3], [45, 4, 7], [9, 6, 10]])
 
# printing initial array
print("initial_array : ", str(ini_array));
 
# Array to be added as column
column_to_be_added = np.array([[1, 2, 3]])
 
# Adding column to numpy array

result=np.hstack((ini_array, column_to_be_added.T))
#this will also work
#result = np.hstack((ini_array, np.atleast_2d(column_to_be_added).T))
 
# printing result
print ("resultant array", str(result))

initial_array :  [[ 1  2  3]
 [45  4  7]
 [ 9  6 10]]
resultant array [[ 1  2  3  1]
 [45  4  7  2]
 [ 9  6 10  3]]


In [ ]:
 
import numpy as np
 
ini_array = np.array([[1, 2, 3], [45, 4, 7], [9, 6, 10]])
 
# printing initial array
print("initial_array : ", str(ini_array));
 
# Array to be added as column
column_to_be_added = np.array([1, 2, 3])
 
# Adding column to numpy array
result = np.column_stack((ini_array, column_to_be_added))
 
# printing result
print ("resultant array", str(result))

In [ ]:
#python code to demonstrate
# adding rows in numpy array
 
import numpy as np
 
ini_array = np.array([[1, 2, 3], [45, 4, 7], [9, 6, 10]])
 
# printing initial array
print("initial_array : ", str(ini_array));
 
# Array to be added as row
row_to_be_added = np.array([1, 2, 3])
 
# Adding row to numpy array
result = np.vstack ((ini_array, row_to_be_added) )
print(row_to_be_added.shape) 
print(ini_array.shape) 
# printing result
print ("resultant array", str(result))

In [ ]:
#5 by 4 array
n=5
k=4
a=np.zeros([n,k])
print(a)
for i in range(n):
    for j in range(k):
        a[i][j]=i+2*j

        
#rowwise colwise sum to be added
#This adds the row
a=np.append(a,[np.sum(a,axis=0)],axis=0)
#This calculates the column
col=np.array([np.sum(a,axis=1)])
print("shape is ",col.shape)
#Finally we add the column
a=np.concatenate((a,col.T),axis=1)
print(a)

In [ ]:
#add a row wise sum list  in array
a=np.array([[0,1,2,3,4,5],
            [10,11,12,13,14,15],
            [20,21,22,23,24,25],
            [30,31,32,33,34,35],
            [40,41,42,43,44,45],
            [50,51,52,53,54,55]])
x=a.sum(0)
print(x)
x=np.array(x)
print(x)
print(x.shape)
print(a.shape)
#a=np.append(a,np.array(x),axis=1)
r=np.vstack((a,x))
r


In [ ]:
import numpy as np

np.random.randint
values = np.random.randint(lower_limit, upper_limit, 10)
values

In [3]:
import numpy as np

np.random.seed(0)
values= np.random.randint( 2, 200, 10)
values




#testing
#16, 124,  30, 118, 173, 161, 113, 111,  30,  18]

array([174,  49, 119, 194,  69, 197, 105,  11,  23,  38])

In [ ]:
[0.34160221, 0.54234533, 0.11764301, 0.27429481],
       [0.30989172, 0.46409958, 0.13890834, 0.89365142],
       [0.18555531, 0.10564703, 0.19165216, 0.66152945]])
       
[[0.94381578, 0.83445753, 0.62749374, 0.54733059],
       [0.23620659, 0.48376324, 0.96704776, 0.84194961],
       [0.29726937, 0.05869515, 0.46087966, 0.68756895]]

In [4]:
import numpy

print("Creating 8X3 array using numpy.arange")
sampleArray = numpy.arange(10, 34, 1)
sampleArray = sampleArray.reshape(8,3)
print (sampleArray)

print("\nDividing 8X3 array into 4 sub array\n")
subArrays = numpy.split(sampleArray, 4) 
print(subArrays)

Creating 8X3 array using numpy.arange
[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]]

Dividing 8X3 array into 4 sub array

[array([[10, 11, 12],
       [13, 14, 15]]), array([[16, 17, 18],
       [19, 20, 21]]), array([[22, 23, 24],
       [25, 26, 27]]), array([[28, 29, 30],
       [31, 32, 33]])]


In [69]:
from PIL import Image
import numpy as np

im = np.array(Image.open('tiger.jfif'))

print(type(im))
# <class 'numpy.ndarray'>

print(im.dtype)
# uint8

print(im.shape)
# (225, 400, 3)
im

<class 'numpy.ndarray'>
uint8
(194, 259, 3)


array([[[224, 231, 125],
        [225, 232, 126],
        [226, 233, 129],
        ...,
        [204, 216, 140],
        [204, 216, 140],
        [204, 216, 140]],

       [[224, 231, 127],
        [225, 232, 128],
        [226, 233, 130],
        ...,
        [204, 216, 140],
        [204, 216, 140],
        [204, 216, 140]],

       [[225, 232, 129],
        [225, 232, 129],
        [226, 232, 132],
        ...,
        [205, 217, 141],
        [205, 217, 141],
        [205, 217, 141]],

       ...,

       [[197, 213,  91],
        [197, 212,  95],
        [198, 212,  99],
        ...,
        [150,  91,  35],
        [150,  91,  35],
        [150,  91,  35]],

       [[176, 213,  73],
        [179, 211,  74],
        [183, 210,  79],
        ...,
        [143,  82,  28],
        [153,  92,  38],
        [164, 103,  49]],

       [[176, 213,  73],
        [179, 211,  74],
        [183, 210,  79],
        ...,
        [143,  82,  28],
        [153,  92,  38],
        [164, 103,  49]]

In [112]:
im_gray = np.array(Image.open('tiger.jfif').convert('L'))

print(im_gray.shape)
pil_img_gray = Image.fromarray(im_gray)
print(pil_img_gray.mode)
# L

pil_img_gray.save('tiger_grey.jfif')
im_gray

(194, 259)
L


array([[216, 217, 219, ..., 203, 203, 203],
       [217, 218, 219, ..., 203, 203, 203],
       [218, 218, 218, ..., 204, 204, 204],
       ...,
       [194, 194, 194, ..., 102, 102, 102],
       [185, 185, 186, ...,  94, 104, 115],
       [185, 185, 186, ...,  94, 104, 115]], dtype=uint8)

In [115]:
from PIL import Image
import numpy as np

im = np.array(Image.open('tiger.jfif'))
print(im)
im_R = im.copy()
im_G = im.copy()
im_B = im.copy()

im_R[:, :, (1, 2)] = 0

im_G[:, :, (0, 2)] = 0

im_B[:, :, (0, 1)] = 0

im_RGB = np.concatenate((im_R, im_G, im_B), axis=0)
# im_RGB = np.hstack((im_R, im_G, im_B))
# im_RGB = np.c_['1', im_R, im_G, im_B]

pil_img = Image.fromarray(im_RGB)
pil_img.save('tiger_concat.jpg')

[[[224 231 125]
  [225 232 126]
  [226 233 129]
  ...
  [204 216 140]
  [204 216 140]
  [204 216 140]]

 [[224 231 127]
  [225 232 128]
  [226 233 130]
  ...
  [204 216 140]
  [204 216 140]
  [204 216 140]]

 [[225 232 129]
  [225 232 129]
  [226 232 132]
  ...
  [205 217 141]
  [205 217 141]
  [205 217 141]]

 ...

 [[197 213  91]
  [197 212  95]
  [198 212  99]
  ...
  [150  91  35]
  [150  91  35]
  [150  91  35]]

 [[176 213  73]
  [179 211  74]
  [183 210  79]
  ...
  [143  82  28]
  [153  92  38]
  [164 103  49]]

 [[176 213  73]
  [179 211  74]
  [183 210  79]
  ...
  [143  82  28]
  [153  92  38]
  [164 103  49]]]
